services:
  voiceops-app:
    build: .
    container_name: voiceops-ai
    expose:
      - "8000"
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      nginx_monitoring_network:
        aliases:
          - voiceops-app  # must match Nginx proxy_pass

networks:
  nginx_monitoring_network:
    external: true